//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintenanceManagement.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaintenanceManagement.Core.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa obszaru.
        /// </summary>
        public static string Area_Name {
            get {
                return ResourceManager.GetString("Area_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulowane.
        /// </summary>
        public static string EmployeeTaskStatus_Canceled {
            get {
                return ResourceManager.GetString("EmployeeTaskStatus_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończone.
        /// </summary>
        public static string EmployeeTaskStatus_Done {
            get {
                return ResourceManager.GetString("EmployeeTaskStatus_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W realizacji.
        /// </summary>
        public static string EmployeeTaskStatus_InProgress {
            get {
                return ResourceManager.GetString("EmployeeTaskStatus_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaplanowane.
        /// </summary>
        public static string EmployeeTaskStatus_Planned {
            get {
                return ResourceManager.GetString("EmployeeTaskStatus_Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propozycja.
        /// </summary>
        public static string EmployeeTaskStatus_Suggestion {
            get {
                return ResourceManager.GetString("EmployeeTaskStatus_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinico.
        /// </summary>
        public static string EmploymentType_Clinico {
            get {
                return ResourceManager.GetString("EmploymentType_Clinico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerendis.
        /// </summary>
        public static string EmploymentType_Gerendis {
            get {
                return ResourceManager.GetString("EmploymentType_Gerendis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manpower.
        /// </summary>
        public static string EmploymentType_Manpower {
            get {
                return ResourceManager.GetString("EmploymentType_Manpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randstad.
        /// </summary>
        public static string EmploymentType_Randstad {
            get {
                return ResourceManager.GetString("EmploymentType_Randstad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lider obszaru.
        /// </summary>
        public static string JobTitle_Area_Leader {
            get {
                return ResourceManager.GetString("JobTitle_Area_Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pracownik kontrollingu.
        /// </summary>
        public static string JobTitle_Controlling_Worker {
            get {
                return ResourceManager.GetString("JobTitle_Controlling_Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektryk.
        /// </summary>
        public static string JobTitle_Electrician {
            get {
                return ResourceManager.GetString("JobTitle_Electrician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pracownik infrastruktóry.
        /// </summary>
        public static string JobTitle_Facility_Worker {
            get {
                return ResourceManager.GetString("JobTitle_Facility_Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kierownik.
        /// </summary>
        public static string JobTitle_Manager {
            get {
                return ResourceManager.GetString("JobTitle_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanik.
        /// </summary>
        public static string JobTitle_Mechanic {
            get {
                return ResourceManager.GetString("JobTitle_Mechanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szef zmiany.
        /// </summary>
        public static string JobTitle_Shift_Leader {
            get {
                return ResourceManager.GetString("JobTitle_Shift_Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pracownik warsztatu.
        /// </summary>
        public static string JobTitle_Workshop_Worker {
            get {
                return ResourceManager.GetString("JobTitle_Workshop_Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string Team_A {
            get {
                return ResourceManager.GetString("Team_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string Team_B {
            get {
                return ResourceManager.GetString("Team_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string Team_C {
            get {
                return ResourceManager.GetString("Team_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string Team_D {
            get {
                return ResourceManager.GetString("Team_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastruktura.
        /// </summary>
        public static string Team_Infrastructure {
            get {
                return ResourceManager.GetString("Team_Infrastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie dotyczy.
        /// </summary>
        public static string Team_NA {
            get {
                return ResourceManager.GetString("Team_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warsztat.
        /// </summary>
        public static string Team_Workshop {
            get {
                return ResourceManager.GetString("Team_Workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uszkodzenie.
        /// </summary>
        public static string ToolEndReason_Damage {
            get {
                return ResourceManager.GetString("ToolEndReason_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymiana.
        /// </summary>
        public static string ToolEndReason_Exchange {
            get {
                return ResourceManager.GetString("ToolEndReason_Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czterobrygadówka.
        /// </summary>
        public static string WorkSchedule_Continuous {
            get {
                return ResourceManager.GetString("WorkSchedule_Continuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jedna zmiana.
        /// </summary>
        public static string WorkSchedule_Regular {
            get {
                return ResourceManager.GetString("WorkSchedule_Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwie zmiany.
        /// </summary>
        public static string WorkSchedule_TwoShifts {
            get {
                return ResourceManager.GetString("WorkSchedule_TwoShifts", resourceCulture);
            }
        }
    }
}
