// <auto-generated />
namespace MaintenanceManagement.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CreatingLibraries : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatingLibraries));
        
        string IMigrationMetadata.Id
        {
            get { return "201404221858431_CreatingLibraries"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
