//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintenanceManagement.Core.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaintenanceManagement.Core.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Name.
        /// </summary>
        public static string Area_Name {
            get {
                return ResourceManager.GetString("Area_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Employee_Address {
            get {
                return ResourceManager.GetString("Employee_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Employee_Area {
            get {
                return ResourceManager.GetString("Employee_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment Start.
        /// </summary>
        public static string Employee_EmploymentStart {
            get {
                return ResourceManager.GetString("Employee_EmploymentStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment Type.
        /// </summary>
        public static string Employee_EmploymentType {
            get {
                return ResourceManager.GetString("Employee_EmploymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string Employee_HomePhone {
            get {
                return ResourceManager.GetString("Employee_HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Administrator.
        /// </summary>
        public static string Employee_IsAdmin {
            get {
                return ResourceManager.GetString("Employee_IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string Employee_JobTitle {
            get {
                return ResourceManager.GetString("Employee_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Employee_Login {
            get {
                return ResourceManager.GetString("Employee_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        public static string Employee_MobilePhone {
            get {
                return ResourceManager.GetString("Employee_MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Employee_Name {
            get {
                return ResourceManager.GetString("Employee_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Employee_Surname {
            get {
                return ResourceManager.GetString("Employee_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Employee_Team {
            get {
                return ResourceManager.GetString("Employee_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Schedule.
        /// </summary>
        public static string Employee_WorkSchedule {
            get {
                return ResourceManager.GetString("Employee_WorkSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string EmployeeTaskStatus_Canceled {
            get {
                return ResourceManager.GetString("EmployeeTaskStatus_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string EmployeeTaskStatus_Done {
            get {
                return ResourceManager.GetString("EmployeeTaskStatus_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string EmployeeTaskStatus_InProgress {
            get {
                return ResourceManager.GetString("EmployeeTaskStatus_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned.
        /// </summary>
        public static string EmployeeTaskStatus_Planned {
            get {
                return ResourceManager.GetString("EmployeeTaskStatus_Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion.
        /// </summary>
        public static string EmployeeTaskStatus_Suggestion {
            get {
                return ResourceManager.GetString("EmployeeTaskStatus_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinico.
        /// </summary>
        public static string EmploymentType_Clinico {
            get {
                return ResourceManager.GetString("EmploymentType_Clinico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerendis.
        /// </summary>
        public static string EmploymentType_Gerendis {
            get {
                return ResourceManager.GetString("EmploymentType_Gerendis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manpower.
        /// </summary>
        public static string EmploymentType_Manpower {
            get {
                return ResourceManager.GetString("EmploymentType_Manpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randstad.
        /// </summary>
        public static string EmploymentType_Randstad {
            get {
                return ResourceManager.GetString("EmploymentType_Randstad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Leader.
        /// </summary>
        public static string JobTitle_Area_Leader {
            get {
                return ResourceManager.GetString("JobTitle_Area_Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlling Worker.
        /// </summary>
        public static string JobTitle_Controlling_Worker {
            get {
                return ResourceManager.GetString("JobTitle_Controlling_Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricial.
        /// </summary>
        public static string JobTitle_Electrician {
            get {
                return ResourceManager.GetString("JobTitle_Electrician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility Worker.
        /// </summary>
        public static string JobTitle_Facility_Worker {
            get {
                return ResourceManager.GetString("JobTitle_Facility_Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string JobTitle_Manager {
            get {
                return ResourceManager.GetString("JobTitle_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanic.
        /// </summary>
        public static string JobTitle_Mechanic {
            get {
                return ResourceManager.GetString("JobTitle_Mechanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Leader.
        /// </summary>
        public static string JobTitle_Shift_Leader {
            get {
                return ResourceManager.GetString("JobTitle_Shift_Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Worker.
        /// </summary>
        public static string JobTitle_Workshop_Worker {
            get {
                return ResourceManager.GetString("JobTitle_Workshop_Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string Team_A {
            get {
                return ResourceManager.GetString("Team_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string Team_B {
            get {
                return ResourceManager.GetString("Team_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string Team_C {
            get {
                return ResourceManager.GetString("Team_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string Team_D {
            get {
                return ResourceManager.GetString("Team_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure.
        /// </summary>
        public static string Team_Infrastructure {
            get {
                return ResourceManager.GetString("Team_Infrastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        public static string Team_NA {
            get {
                return ResourceManager.GetString("Team_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop.
        /// </summary>
        public static string Team_Workshop {
            get {
                return ResourceManager.GetString("Team_Workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damaged.
        /// </summary>
        public static string ToolEndReason_Damage {
            get {
                return ResourceManager.GetString("ToolEndReason_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        public static string ToolEndReason_Exchange {
            get {
                return ResourceManager.GetString("ToolEndReason_Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Name.
        /// </summary>
        public static string ToolType_Name {
            get {
                return ResourceManager.GetString("ToolType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continous.
        /// </summary>
        public static string WorkSchedule_Continuous {
            get {
                return ResourceManager.GetString("WorkSchedule_Continuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        public static string WorkSchedule_Regular {
            get {
                return ResourceManager.GetString("WorkSchedule_Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Shifts.
        /// </summary>
        public static string WorkSchedule_TwoShifts {
            get {
                return ResourceManager.GetString("WorkSchedule_TwoShifts", resourceCulture);
            }
        }
    }
}
